# Generated by Django 3.2.16 on 2023-02-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typer_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialchartypingtest',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
