# Generated by Django 3.2.16 on 2023-02-24 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typer_api', '0002_specialchartypingtest_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialCharTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('test', models.JSONField(verbose_name=models.JSONField())),
                ('results', models.JSONField()),
                ('duration', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_char_test', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SpecialCharTypingTest',
        ),
    ]
