# Generated by Django 3.2.16 on 2023-03-18 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typer_api', '0003_auto_20230224_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='JavaScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('script', models.JSONField(verbose_name=models.JSONField())),
            ],
        ),
        migrations.CreateModel(
            name='JavascriptScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('script', models.JSONField(verbose_name=models.JSONField())),
            ],
        ),
        migrations.CreateModel(
            name='PythonScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('script', models.JSONField(verbose_name=models.JSONField())),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammerTypingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('test', models.JSONField(verbose_name=models.JSONField())),
                ('results', models.JSONField()),
                ('duration', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programming_test', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
