# Generated by Django 3.2.16 on 2023-04-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typer_api', '0004_javascript_javascriptscript_programmertypingtest_pythonscript'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammerTestScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('script', models.JSONField()),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java')], max_length=50)),
                ('length', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='JavaScript',
        ),
        migrations.DeleteModel(
            name='JavascriptScript',
        ),
        migrations.DeleteModel(
            name='PythonScript',
        ),
    ]
