# Generated by Django 3.2.16 on 2023-04-24 15:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typer_api', '0005_auto_20230422_2317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecialCharTest',
            new_name='SpecialCTest',
        ),
    ]
