# Generated by Django 3.2.16 on 2023-07-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typer_api', '0007_auto_20230608_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtypingtest',
            name='wpm',
            field=models.IntegerField(default=0),
        ),
    ]
